---
apiVersion: core.gardener.cloud/v1
kind: ControllerDeployment
metadata:
  name: otelcol
helm:
  ociRepository:
    ref: registry.local.gardener.cloud:5001/helm-charts/gardener-extension-otelcol:v0.1.0-dev
  values: {}
