apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.extension.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.extension.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.extension.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  unhealthyPodEvictionPolicy: AlwaysAllow
